# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formbuilds', '0003_auto_20170505_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='titulo de Encuesta')),
                ('slug', models.SlugField(verbose_name='url encuesta')),
                ('template', models.IntegerField(choices=[(1, 'Template Default'), (2, 'Template LGTB')])),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='formbuilds.Form')),
            ],
        ),
    ]
