# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='template',
            field=models.IntegerField(choices=[(1, 'Template Default'), (2, 'Template LGTB'), (3, 'Template LGTBv2')]),
        ),
    ]
