# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 23:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legend', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Texto'), ('2', 'Verdadero o Falso'), ('3', 'Radio'), ('4', 'Seleccion multiple'), ('5', 'Seleccion'), ('6', 'Cargar documento'), ('7', 'Textarea'), ('8', 'A\xf1o-Mes-D\xeda'), ('9', 'Recortar Imagen')], default=('1', 'Texto'), max_length=2)),
                ('content', models.CharField(max_length=300, verbose_name='Pregunta')),
                ('label', models.SlugField(max_length=200, verbose_name='label')),
                ('required', models.BooleanField(default=True, verbose_name='Campo obligatorio')),
                ('custom_attr', models.TextField(blank=True, default='', max_length=255, null=True)),
                ('help_text', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Texto de ayuda')),
            ],
            options={
                'verbose_name': 'Campo',
                'verbose_name_plural': 'Campos',
            },
        ),
        migrations.CreateModel(
            name='Fieldset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formbuilds.Block')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(default=datetime.datetime.today, help_text='Indica desde cuando aparecera el formulario de registro', verbose_name='V\xe1lido desde')),
                ('valid_to', models.DateField(help_text='Indica hasta cuando aparecera el formulario de registro', verbose_name='V\xe1lido hasta')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='titulo de formulario')),
                ('subtitle', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Subtitulo de formulario')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formbuilds.Field', verbose_name='Campo')),
            ],
            options={
                'verbose_name': 'Opci\xf3n',
                'verbose_name_plural': 'Opciones',
            },
        ),
        migrations.AddField(
            model_name='field',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formbuilds.Form'),
        ),
    ]
