# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilds', '0002_auto_20170505_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='valid_to',
            field=models.DateField(blank=True, default=None, help_text='Indica hasta cuando aparecera el formulario de registro', null=True, verbose_name='V\xe1lido hasta'),
        ),
    ]
