# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilds', '0003_auto_20170505_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_question',
            field=models.BooleanField(default=True),
        ),
    ]
