# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilds', '0004_form_is_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='is_question',
        ),
        migrations.AddField(
            model_name='block',
            name='is_question',
            field=models.BooleanField(default=True),
        ),
    ]
