# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilds', '0005_auto_20170505_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to=b'')),
            ],
        ),
    ]
