# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilds', '0006_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='col_md',
            field=models.CharField(blank=True, choices=[('1', 'col-1'), ('2', 'col-2'), ('3', 'col-3'), ('4', 'col-4'), ('5', 'col-5'), ('6', 'col-6'), ('7', 'col-7'), ('8', 'col-8'), ('9', 'col-9'), ('10', 'col-10'), ('11', 'col-11'), ('12', 'col-12')], max_length=2),
        ),
        migrations.AddField(
            model_name='field',
            name='col_sm',
            field=models.CharField(blank=True, choices=[('1', 'col-1'), ('2', 'col-2'), ('3', 'col-3'), ('4', 'col-4'), ('5', 'col-5'), ('6', 'col-6'), ('7', 'col-7'), ('8', 'col-8'), ('9', 'col-9'), ('10', 'col-10'), ('11', 'col-11'), ('12', 'col-12')], max_length=2),
        ),
    ]
